server:
  port: 7001

#eureka配置
eureka:
  instance:
    hostname: eurek7001.com
  client:
    register-with-eureka: false #表示是否向eureka配置注册中心注册自己
    fetch-registry: false #如果为fslse表示自己是注册中心
    server-url: #监控页面 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/,http://eurek7002.com:7002/eureka/,http://eurek7003.com:7003/eureka/
      defaultZone: http://eurek7002.com:7002/eureka/,http://eurek7003.com:7003/eureka/

spring:
  cloud:
    inetutils:
      ignored-interfaces:
        - VMware.*  # 忽略虚拟机网卡
      use-only-site-local-interfaces: true
      preferred-networks: 192.168.136.* # 优先使用 192.168.0.*