server:
  port: 9527
spring:
  application:
    name: springcloud-zuul-9527

#eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://eurek7001.com:7001/eureka/,http://eurek7002.com:7002/eureka/,http://eurek7003.com:7003/eureka/
  instance:
    insance-id: zuul9527.com

zuul:
  routes:
    mydept.serverId: springcloud-provider-dept
    mysept.path: /mydept/**
  ignored-services: springcloud-provider-dept #忽略这个springcloud-provider-dept